package cn.solomonqbq.bean;

import java.io.Serializable;
import java.util.Date;

public class Instance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.vip
     *
     * @mbggenerated
     */
    private String vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.partition_id
     *
     * @mbggenerated
     */
    private Integer partitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.max_conns
     *
     * @mbggenerated
     */
    private Integer maxConns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.bandwidth
     *
     * @mbggenerated
     */
    private Integer bandwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table instance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.id
     *
     * @return the value of instance.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.id
     *
     * @param id the value for instance.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.name
     *
     * @return the value of instance.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.name
     *
     * @param name the value for instance.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.detail
     *
     * @return the value of instance.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.detail
     *
     * @param detail the value for instance.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.user_id
     *
     * @return the value of instance.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.user_id
     *
     * @param userId the value for instance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.vip
     *
     * @return the value of instance.vip
     *
     * @mbggenerated
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.vip
     *
     * @param vip the value for instance.vip
     *
     * @mbggenerated
     */
    public void setVip(String vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.type
     *
     * @return the value of instance.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.type
     *
     * @param type the value for instance.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.partition_id
     *
     * @return the value of instance.partition_id
     *
     * @mbggenerated
     */
    public Integer getPartitionId() {
        return partitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.partition_id
     *
     * @param partitionId the value for instance.partition_id
     *
     * @mbggenerated
     */
    public void setPartitionId(Integer partitionId) {
        this.partitionId = partitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.status
     *
     * @return the value of instance.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.status
     *
     * @param status the value for instance.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.max_conns
     *
     * @return the value of instance.max_conns
     *
     * @mbggenerated
     */
    public Integer getMaxConns() {
        return maxConns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.max_conns
     *
     * @param maxConns the value for instance.max_conns
     *
     * @mbggenerated
     */
    public void setMaxConns(Integer maxConns) {
        this.maxConns = maxConns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.bandwidth
     *
     * @return the value of instance.bandwidth
     *
     * @mbggenerated
     */
    public Integer getBandwidth() {
        return bandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.bandwidth
     *
     * @param bandwidth the value for instance.bandwidth
     *
     * @mbggenerated
     */
    public void setBandwidth(Integer bandwidth) {
        this.bandwidth = bandwidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.created_time
     *
     * @return the value of instance.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.created_time
     *
     * @param createdTime the value for instance.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.updated_time
     *
     * @return the value of instance.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.updated_time
     *
     * @param updatedTime the value for instance.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Instance other = (Instance) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getVip() == null ? other.getVip() == null : this.getVip().equals(other.getVip()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPartitionId() == null ? other.getPartitionId() == null : this.getPartitionId().equals(other.getPartitionId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getMaxConns() == null ? other.getMaxConns() == null : this.getMaxConns().equals(other.getMaxConns()))
            && (this.getBandwidth() == null ? other.getBandwidth() == null : this.getBandwidth().equals(other.getBandwidth()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getVip() == null) ? 0 : getVip().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPartitionId() == null) ? 0 : getPartitionId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getMaxConns() == null) ? 0 : getMaxConns().hashCode());
        result = prime * result + ((getBandwidth() == null) ? 0 : getBandwidth().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", detail=").append(detail);
        sb.append(", userId=").append(userId);
        sb.append(", vip=").append(vip);
        sb.append(", type=").append(type);
        sb.append(", partitionId=").append(partitionId);
        sb.append(", status=").append(status);
        sb.append(", maxConns=").append(maxConns);
        sb.append(", bandwidth=").append(bandwidth);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}