package cn.solomonqbq.mybatis.mapper;

import cn.solomonqbq.bean.Instance;
import cn.solomonqbq.bean.InstanceParam;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int countByExample(InstanceParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int deleteByExample(InstanceParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int insert(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int insertSelective(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    List<Instance> selectByExample(InstanceParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    Instance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Instance record, @Param("example") InstanceParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Instance record, @Param("example") InstanceParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Instance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Instance record);
}